### ISSUE TITLE
Doesn't work with Github

### ISSUE THREAD

**Issue by lkuchenb** [markmcavoy/androidtoken#13]
When I tried using it for github 2FA, the generated keys don't work. Google Authenticator works though.

**Comment by markmcavoy** [comment]
I'm looking into this issue. How did you provision the token, manually or by scanning the QR code?

**Comment by markmcavoy** [comment]
I think I have located the issue.

So when you scan or enter the key provided on Github its lower case base32. This is where the bug is, Android Token fails to make this upper case before parsing the input.

When I manually create the token and enter the key as upper case it works as expected and the OTP matches that of the Google Authenticator (as created by the QR).

I will create a fix. Additionally I will make the add token input default to base32 as the input format for direct entered keys since most keys are given in base32.

**Comment by lkuchenb** [comment]
Thanks, works fine now!
